config:
  authorName: 'WAKEU Georges Favier'
  authorEmail: 'georgeswakeu21@gmail.com'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always


# Enable Spring Cloud Discovery
eureka:
  client:
    fecthRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    hostname: localhost
    nonSecurePort: 8080


spring:
  cloud:
    discovery:
      enabled: true
  h2:
    console:
      enabled: true