info:
  application:
    name: CATEGORY-SERVICE
    version: 1.0.0
    maintainer:
      author: WAKEU Georges Favier
      email: georgeswakeu21@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    build:
      enabled: true
    env:
      enabled: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/scheriff
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

server:
  servlet:
    context-path: /api

# springdoc:
#   swagger-ui:
#     path: /swagger-ui.html
#     tagsSorter: alpha
#     operationsSorter: alpha
#   api-docs:
#     path: /v3/api-docs
#   show-actuator: true
#   default-produces-media-type: application/json