management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:category-db
    river-class-name: org.h2.Driver
    username: sa
    password: ""

server:
  servlet:
    context-path: /api