# ===== category-service.yml (Config Server) =====
info:
  application:
    name: CATEGORY-SERVICE
    version: 1.0.0
    maintainer:
      author: WAKEU Georges Favier
      email: georgeswakeu21@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    build:
      enabled: true
    env:
      enabled: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:category-db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  servlet:
    context-path: /api
  port: 8081